# Generated by Django 5.1.1 on 2024-09-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='edit_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
