# Generated by Django 5.1.1 on 2024-09-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_edit_count_customer_last_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='major',
        ),
        migrations.AddField(
            model_name='customer',
            name='major_category',
            field=models.CharField(default='IT', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='major_detail',
            field=models.CharField(default='未确定', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='initial_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
