# Generated by Django 5.1.1 on 2024-09-16 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_major_customer_major_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='customer',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
